"""Tests for the yarn.lock parser, serializer and merge.

Round-trip fidelity is the load-bearing property: if serializing an unchanged
document does not reproduce the original bytes, every merge rewrites the whole
file and the cure is worse than the disease.

Run: python3 tests/test_yarnlock.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import yarnlock  # noqa: E402
from merge3 import merge  # noqa: E402

PASS = FAIL = 0
FAILURES = []


def check(name, got, want):
    global PASS, FAIL
    if got == want:
        PASS += 1
    else:
        FAIL += 1
        FAILURES.append(f"{name}\n    got:  {got!r}\n    want: {want!r}")


V1 = '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0":
  version "7.12.11"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.11.tgz#abc"
  integrity sha512-AAA==
  dependencies:
    "@babel/highlight" "^7.10.4"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#def"
  integrity sha512-BBB==
'''

BERRY = '''# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"@adobe/css-tools@npm:4.3.2":
  version: 4.3.2
  resolution: "@adobe/css-tools@npm:4.3.2"
  checksum: 10/973dcb
  languageName: node
  linkType: hard

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  dependencies:
    "other@npm": "npm:^1.0.0"
  languageName: node
  linkType: hard
'''


def test_v1_roundtrip():
    header, doc, dialect = yarnlock.parse(V1)
    check("v1 dialect", dialect, yarnlock.V1)
    check("v1 entries", sorted(doc.keys()), ['"@babel/code-frame@^7.0.0"', "lodash@^4.17.21"])
    check("v1 round-trip byte-identical", yarnlock.serialize(header, doc, dialect), V1)


def test_berry_roundtrip():
    header, doc, dialect = yarnlock.parse(BERRY)
    check("berry dialect", dialect, yarnlock.BERRY)
    check("berry round-trip byte-identical",
          yarnlock.serialize(header, doc, dialect), BERRY)


def test_v1_nested_values():
    _, doc, _ = yarnlock.parse(V1)
    entry = doc['"@babel/code-frame@^7.0.0"']
    check("v1 scalar parsed", entry["version"], '"7.12.11"')
    check("v1 nested block parsed", entry["dependencies"], {'"@babel/highlight"': '"^7.10.4"'})


def test_berry_quoted_key_with_colon():
    """Berry keys contain ':' -- splitting naively would corrupt them."""
    _, doc, _ = yarnlock.parse(BERRY)
    entry = doc['"lodash@npm:^4.17.21"']
    check("berry resolution value", entry["resolution"], '"lodash@npm:4.17.21"')
    check("berry nested dep with colon in key",
          entry["dependencies"], {'"other@npm"': '"npm:^1.0.0"'})


def test_berry_metadata_block():
    _, doc, _ = yarnlock.parse(BERRY)
    check("berry __metadata", doc["__metadata"], {"version": "8", "cacheKey": "10"})


def test_unknown_dialect_refuses():
    try:
        yarnlock.parse("some: yaml\nbut: not a lockfile\n")
        check("unknown dialect refused", "no error", "YarnLockError")
    except yarnlock.YarnLockError:
        check("unknown dialect refused", "raised", "raised")


def test_merge_disjoint_additions():
    """The case the whole tool exists for, at the yarn layer."""
    _, base, dialect = yarnlock.parse(V1)
    header, _, _ = yarnlock.parse(V1)

    ours = dict(base)
    ours["axios@^1.6.0"] = {"version": '"1.6.0"', "integrity": "sha512-AX=="}
    theirs = dict(base)
    theirs["react@^18.0.0"] = {"version": '"18.0.0"', "integrity": "sha512-RE=="}

    merged, conflicts = merge(base, ours, theirs)
    check("yarn disjoint additions: no conflict", conflicts, [])
    check("yarn disjoint additions: both present",
          sorted(k for k in merged if k in ("axios@^1.6.0", "react@^18.0.0")),
          ["axios@^1.6.0", "react@^18.0.0"])
    # and the result must still serialize
    text = yarnlock.serialize(header, merged, dialect)
    _, reparsed, _ = yarnlock.parse(text)
    check("yarn merged output reparses", reparsed, merged)


def test_merge_same_package_different_version_conflicts():
    _, base, _ = yarnlock.parse(V1)
    ours = {k: dict(v) if isinstance(v, dict) else v for k, v in base.items()}
    theirs = {k: dict(v) if isinstance(v, dict) else v for k, v in base.items()}
    # Both sides must move AWAY from base, or there is no disagreement to
    # detect -- base is "4.17.21", so neither side may keep that value.
    ours["lodash@^4.17.21"]["version"] = '"4.17.22"'
    theirs["lodash@^4.17.21"]["version"] = '"4.18.0"'
    _, conflicts = merge(base, ours, theirs)
    check("yarn genuine version disagreement conflicts",
          [c.pretty_path() for c in conflicts], ["lodash@^4.17.21.version"])


def test_real_lockfiles_if_available():
    """Round-trip real lockfiles when they happen to be on disk.

    Skipped rather than failed when absent, so the suite stays runnable, but
    these are the cases that actually matter -- synthetic fixtures do not
    exercise 40,000 lines of real-world formatting.
    """
    for label, path in (("react v1", "/tmp/yl_v1.lock"),
                        ("calcom berry", "/tmp/yl_berry.lock")):
        if not os.path.exists(path):
            continue
        text = open(path).read()
        header, doc, dialect = yarnlock.parse(text)
        check(f"real {label} round-trip byte-identical",
              yarnlock.serialize(header, doc, dialect), text)


def main():
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
    print(f"\n{PASS} passed, {FAIL} failed")
    for f in FAILURES:
        print(f"\nFAIL: {f}")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
